#! /bin/bash

# photomanager
# Copyright (C) Emeric Fremion <scrimet@hotmail.fr>
# Licenced under the terms of the LGLP
# Created on 2020 May 9

source photomanager_settings.sh
source photomanager_functions.sh

############# Arg management ##############
while getopts "$ARGUMENT_STRING" option; do
    case "${option}" in
        s)
            VERBOSITY="s"
            ;;
        l)
            VERBOSITY="l"
            ;;
        q)
            VERBOSITY="q"
            ;;
        o)
            if [ -z "${OPTARG}" ] ; then
                usage
                exit 127
            fi
            OUT_FOLDER="${OPTARG}"
            ;;
        f)
            CLEAN="yes"
            ;;
        c )
            CHECK="yes"
            ;;
        t )
            TEST="yes"
            ;;
        d )
            DEBUG="yes"
            ;;
        v )
            version
            exit 0
            ;;
        h )
            usage            
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))
###########################################

if [ $# -eq 0 ]; then
    WORK_DIR="."
else
    WORK_DIR="$1"
fi

if [ ! -d "$WORK_DIR" ]; then
    say "Folder $1 doesn't exists. Exiting..."
    exit 127
fi

cd "$WORK_DIR" || exit
ensureFolderExists "$OUT_FOLDER"

if [ "$CHECK" = "yes" ]; then
    checkProperRename
    exit 0
fi

# On each file in the folder, call the actual renaming functions
for file in *; do
    if [ -f "$file" ]; then
        if ! RoutineRenameMeta "$file"; then
            RoutineRenameFile "$file"
        fi
    fi
done

# Move the files into the appropriates folder if asked
if [ $CLEAN = "yes" ]; then
    cd "$OUT_FOLDER" || exit
    for file in ./*; do
        if [ -f "$file" ]; then
            moveToYearFolder "$file"
        fi
    done
fi

echo "$TOUCHED file(s) renamed, $MOVED moved to proper year folder."

exit 0
